<?
$PERM["ask"]["G12"]="X";
$PERM["rew"]["G11"]="X";
$PERM["search"]["8"]="W";
$PERM["products"]["8"]="W";
$PERM["services"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["contacts"]["8"]="W";
$PERM["company"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>